### ISSUE TITLE
Images for rep/committee sidebar

### ISSUE THREAD

**Issue by V993** [V993/LegislativeDataAnalytics#68]

**Comment by ZhongweiL** [comment]
@V993 This should be done in the frontend, by storing all the images in a file in the frontend and access them by the image name provided by the backend.

**Comment by V993** [comment]
@ZhongweiL won't that slow down the app? We'd need hundreds of images, idk. In any case we still need the actual images for sure

**Comment by ZhongweiL** [comment]
Don't think it will, the file size is still much smaller than the json files we have in the backend.

**Comment by ZhongweiL** [comment]
@V993 I think it also might be possible to get the image from the git repository directly with a link, you can experiment with that.

**Comment by ZhongweiL** [comment]
image name is all you need from the backend
